[package]
name = "tpt-proc-optimization"
description = "Golden section, Nelder-Mead, and gradient descent optimizers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]


[lints]
workspace = true
