[package]
name = "tpt-proc-fired-equipment"
description = "Part of the tpt-process heat transfer domain"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["furnace", "fired-heater", "combustion", "efficiency"]
categories = ["science", "simulation"]

[dependencies]
tpt-proc-core = { workspace = true }

[lints]
workspace = true
