[package]
name = "tpt-proc-hvac"
description = "Psychrometrics and air-side HVAC calculations"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tpt-proc-core = { workspace = true }

[lints]
workspace = true
