[package]
name = "tpt-proc-reaction"
description = "Part of the tpt-process reaction engineering domain"
readme = "README.md"
keywords = ["kinetics", "arrhenius", "langmuir-hinshelwood", "michaelis-menten"]
categories = ["science", "simulation", "mathematics"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tpt-proc-core = { workspace = true }

[lints]
workspace = true
