[package]
name = "tpt-proc-mass-balance"
description = "Mass balance accounting and weighted data reconciliation"
readme = "README.md"
keywords = ["mass-balance", "data-reconciliation", "material-balance"]
categories = ["science", "simulation", "mathematics"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tpt-proc-core = { workspace = true }

[lints]
workspace = true
