[package]
name = "tpt-proc-database"
description = "General process data store"
readme = "README.md"
keywords = ["data-store", "time-series", "csv", "process-data"]
categories = ["science", "data-structures"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tpt-proc-core = { workspace = true }

[lints]
workspace = true
