[package]
name = "tpt-proc-heat-exchangers"
description = "Part of the tpt-process heat transfer domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tpt-proc-core = { workspace = true }
tpt-proc-heat-transfer = { workspace = true }

[lints]
workspace = true
